// Browser-specific instructions live behind one small seam; Growth OS owns all sends.
// Switching a browser must not change the action/claim/reconciliation protocol.
export const BROWSER_INTERFACES = Object.freeze(['lightpanda-mcp', 'webharness-mcp', 'agent-browser-cli']);

function cliInstructions({ agentBrowserCli, cdpPort, sessionId }) {
  const cli = `${agentBrowserCli} --cdp ${cdpPort} --session ${sessionId}`;
  return `Fallback browser CLI: read its installed contract first with \`${agentBrowserCli} skills get core\` (or \`skills get core --full\`). Use only \`${cli} <command>\` against the EXISTING authenticated Chromium on port ${cdpPort}; never create another profile or browser.
Correct CLI syntax: \`tab list --json\` to discover stable IDs, then \`tab t2\` only if t2 is the observed X tab (not \`tabs\` or \`tab 2\`); \`snapshot -i\` or \`snapshot\` for fresh refs; \`get attr @e1 href\` for an attribute (element first); \`get url\` for current URL. Do not guess command names or reuse stale refs.
If a click is blocked by \`div#layers\` or another covering element, it was NOT dispatched. Observe the covering UI: use its current visible Close/Cancel control only when safe, or \`press Escape\` only if it cannot discard draft content. Re-snapshot before attempting any DIFFERENT pre-send action. Never force-click, script around overlays, or blindly repeat an action with uncertain effects.`;
}

export function browserOperatorContract({ browserTarget, browserInterface, agentBrowserCli, cdpPort, sessionId, browserMcpServer = 'xgrowth_browser', browserFastBackend = 'clearcote', lightpandaMcpServer = 'xgrowth_lightpanda' }) {
  if (browserTarget !== 'linux') return ''; // Windows uses the existing browser-fast + native-dialog policy.
  const fallback = cliInstructions({ agentBrowserCli, cdpPort, sessionId });
  if (browserInterface === 'lightpanda-mcp') {
    return `Primary X browser: native Lightpanda MCP tools from server \`${lightpandaMcpServer}\`: \`mcp__${lightpandaMcpServer}__goto\`, \`mcp__${lightpandaMcpServer}__tree\`, \`mcp__${lightpandaMcpServer}__markdown\`, \`mcp__${lightpandaMcpServer}__extract\`, \`mcp__${lightpandaMcpServer}__waitForState\`, and \`mcp__${lightpandaMcpServer}__getUrl\`. Use these tools for ALL X account reads, For You collection, Mentions, and public-web research; no Agent Browser / WH Browser shell or MCP fallback.
The native Lightpanda MCP launcher reads only the existing X cookies from the local persistent Chromium via an anonymous pipe, without persisting or revealing them. Verify signed-in @ham_zax controls before claiming x_authenticated=true. After \`goto({"url":"https://x.com/home","waitUntil":"domcontentloaded"})\`, wait with \`waitForState({"state":"networkidle"})\` and re-read the semantic tree; URL/title success alone does not establish that an authenticated X timeline rendered. For mentions apply the same readiness and account checks; source ID/permalink and exact text are required. Failure is an explicit authentication/rendering blocker, not proof of no work.
Lightpanda's tools are native goto/tree/extract/etc., not browser-fast observe/execute. Only the Growth OS \`act\` bridge may perform public Post/Reply/Quote writes. Do NOT click X Post/Reply/Quote/Repost/Like/Follow controls yourself; the bridge's Lightpanda publisher owns one guarded send and structural verification. Do not bypass claims or retry an uncertain send. Do not switch browser transports or use unauthenticated Lightpanda output as live X account evidence.`;
  }
  if (browserInterface === 'agent-browser-cli') {
    return `Browser interface: agent-browser-cli (selected explicitly). ${fallback}
Publishing boundary: ONLY the Growth OS bridge \`act\` may send; browser commands here are for observation and pre-send preparation. If any send might have been dispatched, stop UI mutations and reconcile through the existing attempt; never re-send.`;
  }
  if (browserInterface !== 'webharness-mcp') throw new Error(`Unsupported browser interface: ${browserInterface}`);
  return `Browser interface: webharness-mcp (typed opt-in). Use ONLY the Codex typed MCP tools \`mcp__${browserMcpServer}__observe\` and \`mcp__${browserMcpServer}__execute\` from server \`${browserMcpServer}\`. Do not infer they are unavailable without attempting the typed observe call. Do not invoke a shell browser CLI, including skill-lookup commands, when this interface is selected.
To inspect: \`observe\` with browser_target="linux", browser_backend="${browserFastBackend}", scope="interactive" (or "full" for post URLs). Carry returned \`active_tab\` into \`execute\` as tab, with the same target/backend/profile (do not switch backends); execute actions like [{"op":"navigate","url":"https://x.com/home"}] or [{"op":"click","target":"<ref from current observe>"}]. Execute stops on error and never retries. Read completed/failed/unknown/not_run and final_state. Use fresh observe after navigation, stale refs, or a tab mismatch; do not guess a tab or element.
If an X dialog/overlay covers a click, inspect via \`observe\` scope="full"; act only on a newly observed Close/Cancel control when safe, or press Escape when no unsent text can be lost. Re-observe and resolve new refs. Do not force-click, remove overlays through JS, guess selectors, or replay the blocked action without establishing the new state.
If the required MCP observe tool is genuinely absent or rejects the call, do not use agent-browser, wh-browser, or a different browser/profile as an automatic fallback in this run. Use the existing growth-run-finish capability-blocker reporting, make no public mutation, and report the exact MCP tool error or absence. An operator can select agent-browser-cli with X_GROWTH_BROWSER_INTERFACE=agent-browser-cli for a NEW run. No silent mid-run transport switching is permitted.
Publishing boundary: ONLY the Growth OS bridge \`act\` may send; never use direct browser MCP/CLI Post/Reply/Quote clicks as a replacement. An attempted or unknown public send cannot be retried through another browser interface; reconcile the existing attempt or report a blocker. Browser selection never changes claim, health, or duplicate gates.`;
}
