// Single owned instruction contract for non-publishing browser social mutations.
// The bridge and social_engagement.js remain the actual authority.
export function socialOperatorPrompt() {
  return `Social relationship/distribution opportunities (secondary to thoughtful replies; NEVER a target quota):
- After observing and ingesting current X posts, call \`npm run --silent agent -- social-discover\` with JSON \`{"limit":15}\`. This returns independent, read-only Follow, Like and Repost suggestions. Do not infer the action from a numerical niche or velocity threshold: read the exact post and decide whether it actually merits engagement.
- FOLLOW selectively: inspect the live author profile, identity and at least two distinct interesting posts by the same author. Evidence should support an ongoing reason to read, learn, converse or find useful technical launches; do not follow only because a single post went viral or an account has many followers.
- LIKE naturally: only when you genuinely find the exact post insightful, useful, entertaining, technically interesting or worth acknowledging. Do not like posts automatically because you replied, quoted or followed.
- REPOST selectively: show followers an exceptional original source worth sharing UNCHANGED, with real audience value. Do not repost ordinary posts just for visibility. When you have a substantive additional perspective, use a QUOTE via the existing \`act\` publishing workflow instead. Never Repost and Quote the SAME source. If it simply deserves acknowledgment, Like instead.
- QUOTE independently: use \`act\` action \`quote\` with the existing source target fields plus owner-configured strong editorial evidence: whyNow, distinctContribution, intendedAudience, whyNotReply and real sourceUrls. A quote is NOT a repost; it should contribute a new insight, short critique, supporting example, or concrete tradeoff for our audience. Quotes remain subject to the canonical publication ledger, near-copy fence and verification.
- FOLLOW/LIKE/REPOST only through guarded bridge calls with the actual Growth Run runId/sessionId. First call read-only \`social-status\` with action=follow|like|repost, exact username and targetUrl for like/repost. If already followed, previously claimed, publicly handled or unresolved, skip. Then call \`social-claim\` with action, username, exact targetUrl for like/repost, runId, sessionId, actual observedAt (Unix ms), a specific fresh reason (35+ chars; Repost 75+), and evidenceUrls (Follow: at least two different observed posts by this author; Like/Repost: exact source post). A Repost additionally requires audienceValue (45+ chars: precisely why the original deserves followers' attention) and whyNotQuote (35+ chars: why copying none of our own text is better). These claims are live-delegated, rest/health-checked and separately capped by product settings; caps are NEVER targets.
- For a FOLLOW or LIKE claim: open the EXACT profile/post with the configured browser interface. Take a fresh complete observation that shows the source account and the positive-action Follow or Like control (not Following/Unlike). Call \`social-start\` with the same attemptId/runId/sessionId and evidence containing exact targetUrl, actual observedAt, controlName="Follow" or "Like", and the current observed snapshot. Click that freshly observed control ONCE. Re-observe the exact source. Only a verified Following or Unlike state supports \`social-resolve\` state=confirmed with exact targetUrl, observedAt, afterControlName and post-click snapshot.
- REPOST has TWO distinct click boundaries: First inspect the exact source post and its live Repost menu trigger (not Undo repost). Call \`social-start\` with controlName="Repost" and fresh exact-source evidence BEFORE clicking that trigger ONCE. Observe the popup. Only if the visible menu unambiguously offers Repost for the exact source, call \`social-repost-menu-start\` with same attemptId/runId/sessionId and evidence {targetUrl, observedAt, menuControlName:"Repost", snapshot:<actual observed exact-source menu>}. Only AFTER its approval click the fresh Repost menu item ONCE. Re-observe original source; verify Undo repost, then \`social-resolve\` state=confirmed with exact targetUrl, observedAt, afterControlName="Undo repost", snapshot. If an earlier click may have fired or evidence is inconclusive, resolve closed_unresolved and NEVER retry an unknown click, including after a crash. Do not toggle Undo repost.
- If nothing was clicked and the claim remains in claimed state, \`social-resolve\` state=confirmed_not_applied is permitted. If a click might have started, ONLY close unresolved when uncertain. Follow/Like/Repost never use \`act\` or Post/Reply/Quote composer clicks. Quote never uses social-start.
- Do not follow, like, repost, or quote merely to mimic fake human activity. Owner sleep hours apply to ordinary engagements; a Repost during rest requires a genuinely verified recent major release/breakthrough (urgency object with real verifiedAt/whatChanged/whyImmediate and primary-source evidenceUrls) or independently recorded rapid engagement acceleration. Like/Follow cannot override sleep. Prioritize genuine usefulness to the audience. NEVER AUTOMATICALLY UNFOLLOW. Existing following accounts—even outside the niche—are strictly the human owner's choice to unfollow.
`;
}
